name: Build code and run security scans

on:
  push:
    branches:
      - master  # Specify the branches you want this workflow to run on

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Compile the Code
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  semgrep:
    needs: build
    runs-on: ubuntu-latest
    name: SAST [Semgrep Scan]
    steps:
      - uses: actions/checkout@v3
      - name: Run Semgrep
        run: docker run --rm -v "${PWD}:/src" returntocorp/semgrep semgrep --config auto --output semgrep-output.json --json
      - uses: actions/upload-artifact@v3
        with:
          name: semgrep
          path: semgrep-output.json
        continue-on-error: true
        if: always()

  oast:
    needs: semgrep
    runs-on: ubuntu-20.04
    name: SCA [Scan with Safety]
    steps:
      - uses: actions/checkout@v3
      - name: Run Safety
        run: docker run --rm -v $(pwd):/src hysnsec/safety check -r requirements.txt --json > oast-results.json
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        with:
          name: Safety
          path: oast-results.json
        if: always()

  bundler:
    needs: oast
    runs-on: ubuntu-20.04
    name: SCA [Bundler Audit]
    steps:
      - uses: actions/checkout@v3
      - run: docker run --rm -v $(pwd):/src -w /src hysnsec/bundle-audit check --format json --output bundle-audit-output.json
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        with:
          name: bundler-audit
          path: bundle-audit-output.json
        if: always()

  zap_scan:
    needs: bundler
    runs-on: ubuntu-latest
    name: DAST [OWASP ZAP]
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          docker_name: 'owasp/zap2docker-weekly'
          target: 'http://testphp.vulnweb.com/'  # Replace with your target URL
          cmd_options: '-a'
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v3
        with:
          name: ZAP Reports
          path: |
            zap_report.html
            zap_report.json

  IAC:
    needs: bundler
    runs-on: ubuntu-20.04
    name: IAC [Terraform Security Scan]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Terraform Security Scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
